- name: 1a. Add APT GPG signing key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db state=present
  become: true
  become_method: sudo

- name: 1b. Add APT repository
  apt_repository: repo='deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu trusty main' state=present update_cache=yes
  become: true
  become_method: sudo

- name: 1c. Install MariaDB server package
  apt: name=mariadb-server state=present
  become: true
  become_method: sudo

- name: 2. Start Mysql Service
  service: name=mysql state=started enabled=true
  become: true
  become_method: sudo

- name: Install python Mysql package #required for mysql_db tasks
  apt: name=python-mysqldb state=present
  become: true
  become_method: sudo

- name: 3. Create a new database
  mysql_db: name=demo state=present collation=utf8_general_ci
  become: true
  become_method: sudo

- name: 4. Create a database user
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present
  become: true
  become_method: sudo

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql
  become: true
  become_method: sudo
  become_user: marajade

- name: 5b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo
  become: true
  become_method: sudo

- name: 6. Install MySQL extension for PHP
  apt: name=php5-mysql state=present
  become: true
  become_method: sudo
