- name: 1. install Apache
  apt: name=apache2 state=present
  become: true
  become_method: sudo

- name: 2. install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present
  become: true
  become_method: sudo

- name: 3. start Apache
  service: name=apache2 state=running enabled=yes
  become: true
  become_method: sudo

- name: 4. install Hello World PHP script
  copy: src=/etc/ansible/roles/web/templates/index.html dest=/var/www/html/index.html mode=0664
  become: true
  become_method: sudo
